---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-health-monitor-config
  namespace: kube-system
data:
  config.yaml: |
    checkers:
      - name: "internal-dns-checker"
        type: "dns"
        interval: "10s"
        timeout: "5s"
        dnsConfig:
          domain: "kubernetes.default.svc.cluster.local"
      - name: "external-dns-checker"
        type: "dns"
        interval: "10s"
        timeout: "5s"
        dnsConfig:
          domain: "mcr.microsoft.com"
      - name: "pod-startup-checker"
        type: "podStartup"
        interval: "1m"
        timeout: "30s"
