---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-health-monitor-config
  namespace: kube-system
data:
  config.yaml: |
    checkers:
      - name: "internal-coredns"
        type: "dns"
        interval: "10s"
        timeout: "5s"
        dnsConfig:
          domain: "kubernetes.default.svc.cluster.local"
          queryTimeout: "2s"
      - name: "external-coredns"
        type: "dns"
        interval: "10s"
        timeout: "5s"
        dnsConfig:
          domain: "mcr.microsoft.com"
          queryTimeout: "2s"
      - name: "internal-localdns"
        type: "dns"
        interval: "10s"
        timeout: "5s"
        dnsConfig:
          domain: "kubernetes.default.svc.cluster.local"
          checkLocalDNS: true
          queryTimeout: "2s"
      - name: "external-localdns"
        type: "dns"
        interval: "10s"
        timeout: "5s"
        dnsConfig:
          domain: "mcr.microsoft.com"
          checkLocalDNS: true
          queryTimeout: "2s"
      - name: "pod-startup"
        type: "podStartup"
        interval: "1m"
        timeout: "30s"
        podStartupConfig:
          syntheticPodNamespace: "kube-system"
          syntheticPodLabelKey: "kubernetes.azure.com/cluster-health-monitor-checker-synthetic"
          syntheticPodStartupTimeout: "5s"
          maxSyntheticPods: 10
          image: "mcr.microsoft.com/oss/v2/kubernetes/pause:3.9"
      - name: "api-server"
        type: "apiServer"
        interval: "30s"
        timeout: "5s"
        apiServerConfig:
          namespace: "kube-system"
          labelKey: "kubernetes.azure.com/cluster-health-monitor-checker-apiserver"
          mutateTimeout: "1s"
          readTimeout: "1s"
          maxObjects: 10
