---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-health-monitor
  namespace: kube-system
---
# Role for accessing kube-dns and endpointslices in kube-system.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cluster-health-monitor-kube-system-reader
  namespace: kube-system
rules:
  - apiGroups: [""]
    resources: ["services"]
    resourceNames: ["kube-dns"]
    verbs: ["get"]
  - apiGroups: ["discovery.k8s.io"]
    resources: ["endpointslices"]
    verbs: ["list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cluster-health-monitor-kube-system-reader
  namespace: kube-system
subjects:
  - kind: ServiceAccount
    name: cluster-health-monitor
    namespace: cluster-health-monitor
roleRef:
  kind: Role
  name: cluster-health-monitor-kube-system-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: synthetic-pod-manager
  namespace: kube-system
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "create", "list", "delete"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cluster-health-monitor-pod-manager
  namespace: kube-system
subjects:
  - kind: ServiceAccount
    name: cluster-health-monitor
    namespace: kube-system
roleRef:
  kind: Role
  name: synthetic-pod-manager
  apiGroup: rbac.authorization.k8s.io