apiVersion: health.aks.io/v1alpha1
kind: HealthSignal
metadata:
  name: clusterhealth-example
spec:
  type: NodeHealth
  target:
      nodeName: aks-agentpool-31207608-vmss000000
status:
  startedAt: "2026-01-23T14:14:00Z"
  finishedAt: "2026-01-23T14:19:00Z"
  condition:
    - type: Healthy
      status: "True"
      reason: NodeResponsive
      message: Node is responsive and healthy
