apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: clusterhealthmonitor-azureblob-sc
provisioner: blob.csi.azure.com
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  skuName: Standard_LRS
  protocol: fuse
