# This Github Action will build and publish images to Azure Container Registry(ACR), from where the published images will be automatically
# pushed to the trusted registry, Microsoft Container Registry(MCR).

name: build_and_publish_acr
on:
  workflow_dispatch:
    inputs:
      releaseTag:
        description: 'Release tag to publish images, defaults to the latest one'
        type: string

permissions:
  id-token: write
  contents: read

env:
  # `public` indicates images to MCR wil be publicly available, and will be removed in the final MCR images
  REGISTRY_REPO: public/aks/cluster-health-monitor
  CLUSTER_HEALTH_MONITOR_IMAGE_NAME: cluster-health-monitor
jobs:
  prepare-variables:
    runs-on: ubuntu-latest
    outputs:
      release_tag: ${{ steps.vars.outputs.release_tag }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: 'Set output variables'
      id: vars
      run: |
        # set the image version
        RELEASE_TAG=${{ inputs.releaseTag }}
        if [ -z "$RELEASE_TAG" ]; then
          RELEASE_TAG=`git describe --tags $(git rev-list --tags --max-count=1)`
          echo "The user input release tag is empty, will use the latest tag $RELEASE_TAG."
        fi
        echo "release_tag=$RELEASE_TAG" >> $GITHUB_OUTPUT

        # NOTE: As exporting a variable from a secret is not possible, the shared variable registry obtained
        # from AZURE_REGISTRY secret is not exported from here.

  publish-images:
    runs-on:
      labels: [ self-hosted, "1ES.Pool=1es-aks-cluster-health-monitor-pool-ubuntu" ]
    needs: prepare-variables
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ needs.prepare-variables.outputs.release_tag }}
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        driver-opts: image=mcr.microsoft.com/oss/v2/moby/buildkit:v0.18.1
    
    - name: 'Login the ACR'
      run: |
        az login --identity 
        az acr login -n ${{ secrets.AZURE_REGISTRY }}
    
    - name: Build and publish cluster-health-monitor
      uses: docker/build-push-action@v6
      with:
        context: .
        file: docker/cluster-health-monitor.Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ secrets.AZURE_REGISTRY }}/${{ env.REGISTRY_REPO}}/${{ env.CLUSTER_HEALTH_MONITOR_IMAGE_NAME }}:${{ needs.prepare-variables.outputs.release_tag }}
