name: Trivy Vulnerability Scan

on:
  push:
    branches: 
      - main
    tags: 
      - 'v*.*.*'
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

env:
  IMAGE_NAME: cluster-health-monitor

jobs:
  vulnerability-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set image variables
        id: vars
        run: |
          REGISTRY=$(echo "ghcr.io/${{ github.repository }}" | tr [:upper:] [:lower:])
          VERSION=$(git rev-parse --short=7 HEAD)
          echo "registry=$REGISTRY" >> $GITHUB_OUTPUT
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "image=$REGISTRY/${{ env.IMAGE_NAME }}:$VERSION" >> $GITHUB_OUTPUT
      
      - name: Build image
        run: make docker-build-cluster-health-monitor
        env:
          REGISTRY: ${{ steps.vars.outputs.registry }}
          CLUSTER_HEALTH_MONITOR_IMAGE_NAME: ${{ env.IMAGE_NAME }}
          CLUSTER_HEALTH_MONITOR_IMAGE_VERSION: ${{ steps.vars.outputs.version }}
          OUTPUT_TYPE: type=docker
          PLATFORM: linux/amd64
      
      - name: Run Trivy scan
        uses: aquasecurity/trivy-action@0.33.0
        with:
          scan-type: image
          image-ref: ${{ steps.vars.outputs.image }}
          format: table
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: os,library
          scanners: vuln,secret
          severity: CRITICAL,HIGH,MEDIUM,LOW,UNKNOWN
          timeout: 5m0s
        env:
          TRIVY_DB_REPOSITORY: mcr.microsoft.com/mirror/ghcr/aquasecurity/trivy-db
